### ISSUE TITLE
Request: FAQ Addition - What's the default image upload size limit?

### ISSUE THREAD

**Issue by mcat-ee** [tootsuite/documentation#153]
See title, and additionally is there a way to inspect an instance's upload size limit? I've noticed that if Tusky can't upload to an instance (due to the Mastodon limit, reverse-proxy limit, or load balancer limit) it will give a non-descriptive error - support for getting an instance's limit could somewhat improve this.

**Comment by ashfurrow** [comment]
This is configurable per-instance but the default image upload size is [eight megabytes](https://github.com/tootsuite/mastodon/blob/7d36a76180ce6bb207c6755bdffeba0b4edb6824/app/models/media_attachment.rb#L32). Would you be able to submit a pull request adding this to the docs?

**Comment by mcat-ee** [comment]
@ashfurrow Sure! Should the method be to change the 8 do a different integer?

**Comment by ashfurrow** [comment]
It would be a chance to the code, but the image/gif are going to get resized down to a smaller resolution (this isn't configurable on purpose, because those images will need to get stored on other instances). So for large images, use of an external host like flickr or imgur is advisable. 

Does that make sense? Happy to clarify anything.

**Comment by mcat-ee** [comment]
@ashfurrow Thanks for informing me! (: Since that happens transparently it might be good to mention it, but press that the upload size limiting occurs before that point.
