### ISSUE TITLE
Maintenance Task frequency is unclear

### ISSUE THREAD

**Issue by wolfteeth** [tootsuite/documentation#195]
I have a daily cron script that runs all my Mastodon maintenance tasks. I'm starting to believe this is not adequate for PuSH subscription refresh. I have found subscriptions dying even on days when the script appeared to have been run.

Keeping feeds from dying should be a solved problem, but I have no idea how often I should refresh subscriptions to ensure a seamless experience with no lost messages. Recommended frequency should be clearly outlined in the documentation. Do I need to do it every hour? Every minute? At what point is it guaranteed to revive expiring subscriptions?

**Comment by wxcafe** [comment]
Since [v1.3.3](https://github.com/tootsuite/mastodon/releases/tag/v1.3.3) PuSH subscriptions refreshes are run through Sidekiq, so you shouldn't have any more problems with that.

The daily task should be run every day as is said in the docs already, if you've had problems in the past it's probably coming from something else.
