### ISSUE TITLE
Vagrant install bugs out on the SSH command

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [tootsuite/documentation#470]
Windows 10, latest Vagrant and Mastodon repo.

error: https://hastebin.com/zapeqohepo.vbs

**Comment by wxcafe** [comment]
ping @nolanlawson :)

**Comment by argrath** [comment]
On Windows host, you can't build Mastodon with out-of-the-box Vagrantfile, because the build script try to make symlinks on the shared folder, but it can't on Windows filesystem.

[My customized Vagrantfile](https://gist.github.com/argrath/b86b789f99e948780984bbf2b96ff798) may help.
(You may want to change network settings.)

**Comment by wxcafe** [comment]
re-ping @nolanlawson

**Comment by ThatNerdyPikachu** [comment]
re-re-ping @nolanlawson

**Comment by ThatNerdyPikachu** [comment]
re-re-re-ping @nolanlawson

**Comment by ThatNerdyPikachu** [comment]
re-re-re-re ping @nolanlawson

**Comment by nightpool** [comment]
why are we pinging nolanlawson. let's stop pinging nolanlawson.

**Comment by ThatNerdyPikachu** [comment]
f

**Comment by argrath** [comment]
So, what we should do to get any progress about this issue other than pinging nolanlawson?
