### ISSUE TITLE
Unsure how to make PostgreSQL host, user, pass?

### ISSUE THREAD

**Issue by brograhamer** [tootsuite/documentation#582]
I've done the Standalone guide, step by step, but have trouble towards the end of the commands. I'm unsure when running `RAILS_ENV=production bundle exec rake mastodon:setup` how to even make everything required. Little help?

Feels like I'm 95% there otherwise. Little help for a noob?

**Comment by cosmopath** [comment]
Contrary to what the guide said, I had to assign a password to the PostgreSQL user to get this to work, because the setup wouldn't accept a blank password.

Recall this part of the guide: https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md#postgresql-database-creation

There was a PostgreSQL username named "mastodon" made, but it was assigned no password. What I did was the following:

```
sudo -u postgres psql
\password mastodon
[enter a new password, doesn't matter what it is]
\q
```

Now when you run the setup, you can actually enter the password with it accepting it! PostgreSQL host is just localhost (so enter `127.0.0.1`), keep the database name as `postgres`, and the username is `mastodon`.

**Comment by zeitrechnen** [comment]
I had no issues but I think the documentation could be more detailed about this point.

> Note that we do not set up a password of any kind, this is because we will be using ident authentication. This allows local users to access the database without a password.

So, during the setup wizard I didn't specify any password, which was accepted. But what I don't understand, is the password empty now? Is this setup insecure? How can I check that Postgres really uses  ident authentication and that the setup is secure?

**Comment by nightpool** [comment]
postgres won't allow password based login for accounts without a password,
so there's no reason to be concerned about adding an account without a
password. indeed, it's much more secure to add an account without a
password then it is to add an account WITH a password

**Comment by Gargron** [comment]
There's a lot of information to unpack here. IDENT authentication means the connection to postgres is established as the unix user, so if Mastodon runs as the unix user "mastodon", if a corresponding passwordless postgres user "mastodon" exists, the connection will work. This only works when using the postgres socket (/var/run/postgresql) and not tcp host/port (localhost:5432). It's minimal amount of configuration and it's pretty secure, if your unix user can be accessed by an attacker, then a postgres password wouldn't help since the password would need to be readable to the unix user anyway.

When you need to use a tcp host/port connection, such as: when you need to use pgBouncer, or have postgresql on a different machine, you cannot use IDENT and need to use password-based authentication. There's a rabbit hole of postgres documentation there, as you likely need to edit /etc/postgresql/9.6/main/pg_hba.conf to whitelist that method of authentication for a specific user/host.

**Comment by zeitrechnen** [comment]
Thank you so much for all your kind and detailed answers!
