### ISSUE TITLE
account_followers limit

### ISSUE THREAD

**Issue by drequivalent** [tootsuite/documentation#621]
Why limit how many followers I can get?
Why limit to only 80?

I want to be able to see all my followers, as I maintain a group bot. It limits a number of members to 80.

**Comment by drequivalent** [comment]
Oops, it's documentation. Apologies.

**Comment by Gargron** [comment]
You can get... 80 per page? What are you asking about? Number of followers you can accrue is obviously not limited

**Comment by drequivalent** [comment]
In the API documentation:
```
Getting an account's followers:
GET /api/v1/accounts/:id/followers
limit | Maximum number of followers to get (Default 40, Max 80)
```

**Comment by Gargron** [comment]
Paginate

**Comment by levlaz** [comment]
@drequivalent 

> Surely, I can raise the limit but only to 80. Why should this limit exist though?

This is common to how most APIs work. When you have many records rather than sending them all in one massive payload it will send you a subset and allow you to paginate to request more. This makes it easier on both the server and the client. 

You can look at [this example from the python API wrapper](https://github.com/halcy/Mastodon.py/blob/f8ba37b42e529b90b10050610098cd648f3a3572/mastodon/Mastodon.py#L1426) that shows how this works in practice.
