### ISSUE TITLE
Please specify version requirements for the dependencies

### ISSUE THREAD

**Issue by RedL0tus** [tootsuite/documentation#626]
The story is, I'm hosting my own Mastodon instance on CentOS 7 since last year. 
Today when I upgrading it to v2.4.0, it failed at migrating databases because the version of PostgreSQL provided in CentOS 7 main repo was too low (which is around 9.2) which doesn't support `jsonb` data type. 
But there isn't any warning before upgrading, both in the documentation and release notes (only Ruby version are noted).

Right now I've just upgraded PostgreSQL to the newest stable version (10.X).

I think if there is a warning of minimum version requirement would be useful for people who are hosting Mastodon instances with distros other than Ubuntu, just like me.

**Comment by levlaz** [comment]
This should probably be added to the [upgrade notes](https://github.com/tootsuite/mastodon/releases/tag/v2.4.0).

I think this is a good idea, I think a separate document for CentOS may be necessary since many of the versions of software are quite old. 

IMHO running Mastodon in Docker on CentOS 7 is probably the *easiest* approach. 

In any case, keeping track of specific versions of things would be really nice. The closest thing we have to a recommendation what I can see is [what is running in CI](https://github.com/tootsuite/mastodon/blob/master/.circleci/config.yml#L132).
