### ISSUE TITLE
Config example may need updating, also 'unexpectedly closed the connection'

### ISSUE THREAD

**Issue by songproducer** [tootsuite/documentation#64]
I had to add this to the config file

```
http {
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}
```
and commented out the lines for ssl (until I can get the lets encrypt ssl working, but I'm getting "unexpectedly closed the connection" now.

When I run nginx -g 'daemon off;'
I get
```
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
```

**Comment by wxcafe** [comment]
This is related to Let's Encrypt and nginx, and not to Mastodon. It's out of scope for this project. 

The config examples work for people who know what they're working with. Your problem here is probably due to the fact that you have to configure LE before setting up mastodon and using the config example. I'm closing this issue and I invite you to have a look at a Let's Encrypt tutorial

**Comment by songproducer** [comment]
Ok thanks!
