### ISSUE TITLE
OAuth documentation on retrieving an access token are out of date.

### ISSUE THREAD

**Issue by masterodie** [tootsuite/documentation#667]
Found working instructions here https://github.com/spaceottercode/Mastodon-OAuth-Documentation

**Comment by palant** [comment]
Yes, I made the same experience. The difference is mostly that `/oauth/authorize` endpoint in step 4 gives you an authorization code rather than a refresh token. So in step 2 you have to send `grant_type=authorization_code` and `code=<authorization_code>`. Finally, it's my understanding that the access token no longer expires, so refreshing isn't necessary.

**Comment by masterodie** [comment]
I think this should be sufficient for now.
