### ISSUE TITLE
What's the difference between authorization and access token ?

### ISSUE THREAD

**Issue by mathieunicolas** [tootsuite/documentation#776]
Hello, 

I wanted to attach the label "question" but I can't find where.
I'm doing research for a project based on mastodon, and I've read the documentation about developing mastodon apps.
I would like to make a web app that could use API to create an account if the user doesn't have one, or just allow user to authorize the app to post on mastodon if he/she already has an account.

(1) `POST to 	https://mastodon.example/api/v1/apps`
Will return client_id and client_secret

(2) `POST to 	https://mastodon.example/oauth/token`
Will return an ACCESS_TOKEN
First bug in my head : what will this access token allow me to do ? I've seen getting the followings of an account, for example ? What if the scopes defined in (1) include read write follow push ? Can this token write anything ?

(3) browser `https://mastodon.example/oauth/authorize
?client_id=CLIENT_ID
&scope=read+write+follow+push
&redirect_uri=urn:ietf:wg:oauth:2.0:oob
&response_type=code`
With a client_id (no client_secret here ?) I can get a link in which the user has to click on "authorize" to get an authorization code (can be used one time) my app will need to be able to interact with mastodon as if it was the user, am I right ?

(4) `POST to 	https://mastodon.example/oauth/token`
this time, with client_id, client_secret, authorization code, I get another access code. With this access token, I can do more things in mastodon, than with (2) access token, am I right ?

If everything in (1) -> (4) is correct, I can have two access tokens ? Do I have to get the (2) access token to be able to get the (4) access token ?

And my last questions are about the user's access token. Is it built to last "forever" ? As soon as I keep my access token, I will be able to read write follow push in the name of my user ?
There something I don't get : let's imagine the journey of a lambda user on my future web app : 
- connection to my.domain.tld (my web app)
- has or has not mastodon account, I will at the end get her/his access token
- I keep the access token securely
- user empty cache and cookies
- come back to my.domain.tld
-> is there any way for my user to login again with masto login/password, _in my.domain.tld_ ? Or do I have to setup a different login system (like, a one-time email login for example, which way would you recommand to setup a secure way for my user to be able to enjoy her/his access token in my web app without having to deal with login/password in masto, AND login2/password2 in my.domain.tld ?)

I am so sorry to ask you some noobie questions, but I'm trying to have an overview of my project and I feel quite lost on some technical points.

Thanks a lot for bringing us mastodon, and for your answer !
Have a good day

**Comment by trwnh** [comment]
>First bug in my head : what will this access token allow me to do ? I've seen getting the followings of an account, for example ? What if the scopes defined in (1) include read write follow push ? Can this token write anything ?

There are two flows -- one for authorizing a user, one for simply accessing certain client methods.

To authorize a user, you would perform 1 -> 3 -> 4. The token you generated will be able to perform actions on behalf of the authorized user. If you skip step 3 or leave out authorization-related parameters in step 4, then your token has no associated user and cannot be used with any methods that require a user.

A token without a user can be used to fetch follower/following lists, yes -- and also, some instances operate in an auth-required mode that disables access without a token. https://docs.joinmastodon.org/client/token/#methods

While it is possible to request additional scopes with a client-only token, this currently doesn't mean much because there aren't any methods that use a scope other than `read` or perhaps `push`. Almost every single `write` method also requires a user. However, there is one exception -- registering a user. Creating a new user only requires an app token and `write:accounts`. https://docs.joinmastodon.org/methods/accounts/

>If everything in (1) -> (4) is correct, I can have two access tokens ? Do I have to get the (2) access token to be able to get the (4) access token ?

You can generate as many tokens as you need. If you want to do stuff with a user account, you don't need (2), you only need (4). As explained above, step 3 is optional. If you do it, you end up at (4), and if you do not, you end up at (2).

>And my last questions are about the user's access token. Is it built to last "forever" ? As soon as I keep my access token, I will be able to read write follow push in the name of my user ?

The token lasts until it is revoked. This can be done by the user at any time, if they do not want to allow an app to access their account anymore. 

>is there any way for my user to login again with masto login/password, in my.domain.tld ? Or do I have to setup a different login system

The user would have to login again. You do have the option of setting up your own account system and allowing users to link their Mastodon account via the settings, though.

**Comment by mathieunicolas** [comment]
Thank you very much for you explanation, that makes everything crystal clear.
I consider this issue closed, and wish you a nice day !
